-- Tabela para a entidade base User
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_state VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    full_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- Tabela para a subclasse Account (estratégia JOINED)
CREATE TABLE accounts (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_accounts_on_users FOREIGN KEY (id) REFERENCES users (id)
);

-- Tabela para UserRole
CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    model_guid UUID NOT NULL UNIQUE
);

-- Tabela para Session
CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_state VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    session_token UUID NOT NULL UNIQUE,
    logout_time TIMESTAMP,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_sessions_on_users FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Tabela de junção para o relacionamento User <-> UserRole
CREATE TABLE user_role_assignments (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_assignments_on_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_assignments_on_roles FOREIGN KEY (role_id) REFERENCES user_roles (id)
);

-- Tabela de junção para o auto-relacionamento de UserRole
CREATE TABLE role_grantable_roles (
    role_id BIGINT NOT NULL,
    grantable_role_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, grantable_role_id),
    CONSTRAINT fk_grantable_on_roles FOREIGN KEY (role_id) REFERENCES user_roles (id),
    CONSTRAINT fk_grantable_on_grantable_roles FOREIGN KEY (grantable_role_id) REFERENCES user_roles (id)
);