
    create table accounts (
        id bigint not null,
        primary key (id)
    );

    create table role_grantable_roles (
        grantable_role_id bigint not null,
        role_id bigint not null,
        primary key (grantable_role_id, role_id)
    );

    create table sessions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logout_time timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        session_token uuid not null unique,
        ip_address varchar(45),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        user_agent varchar(255),
        primary key (id)
    );

    create table user_role_assignments (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table user_roles (
        id bigint generated by default as identity,
        model_guid uuid not null unique,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        full_name varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKlsevhk46j1mfa8r9bak4tr4x3 
       foreign key (id) 
       references users;

    alter table if exists role_grantable_roles 
       add constraint FKik102cto3k67xqweb7k1vdw7k 
       foreign key (grantable_role_id) 
       references user_roles;

    alter table if exists role_grantable_roles 
       add constraint FKp82b1hlqcctsf88w8fcb31n10 
       foreign key (role_id) 
       references user_roles;

    alter table if exists sessions 
       add constraint FKruie73rneumyyd1bgo6qw8vjt 
       foreign key (user_id) 
       references users;

    alter table if exists user_role_assignments 
       add constraint FKgn3qd4tmot5ikyaplglaowd9i 
       foreign key (role_id) 
       references user_roles;

    alter table if exists user_role_assignments 
       add constraint FKrb42ra1ptis8nx3g4wotuf003 
       foreign key (user_id) 
       references users;

    create table accounts (
        id bigint not null,
        primary key (id)
    );

    create table role_grantable_roles (
        grantable_role_id bigint not null,
        role_id bigint not null,
        primary key (grantable_role_id, role_id)
    );

    create table sessions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logout_time timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        session_token uuid not null unique,
        ip_address varchar(45),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        user_agent varchar(255),
        primary key (id)
    );

    create table user_role_assignments (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table user_roles (
        id bigint generated by default as identity,
        model_guid uuid not null unique,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        full_name varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKlsevhk46j1mfa8r9bak4tr4x3 
       foreign key (id) 
       references users;

    alter table if exists role_grantable_roles 
       add constraint FKik102cto3k67xqweb7k1vdw7k 
       foreign key (grantable_role_id) 
       references user_roles;

    alter table if exists role_grantable_roles 
       add constraint FKp82b1hlqcctsf88w8fcb31n10 
       foreign key (role_id) 
       references user_roles;

    alter table if exists sessions 
       add constraint FKruie73rneumyyd1bgo6qw8vjt 
       foreign key (user_id) 
       references users;

    alter table if exists user_role_assignments 
       add constraint FKgn3qd4tmot5ikyaplglaowd9i 
       foreign key (role_id) 
       references user_roles;

    alter table if exists user_role_assignments 
       add constraint FKrb42ra1ptis8nx3g4wotuf003 
       foreign key (user_id) 
       references users;

    create table accounts (
        id bigint not null,
        primary key (id)
    );

    create table role_grantable_roles (
        grantable_role_id bigint not null,
        role_id bigint not null,
        primary key (grantable_role_id, role_id)
    );

    create table sessions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logout_time timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        session_token uuid not null unique,
        ip_address varchar(45),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        user_agent varchar(255),
        primary key (id)
    );

    create table user_role_assignments (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table user_roles (
        id bigint generated by default as identity,
        model_guid uuid not null unique,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        full_name varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKlsevhk46j1mfa8r9bak4tr4x3 
       foreign key (id) 
       references users;

    alter table if exists role_grantable_roles 
       add constraint FKik102cto3k67xqweb7k1vdw7k 
       foreign key (grantable_role_id) 
       references user_roles;

    alter table if exists role_grantable_roles 
       add constraint FKp82b1hlqcctsf88w8fcb31n10 
       foreign key (role_id) 
       references user_roles;

    alter table if exists sessions 
       add constraint FKruie73rneumyyd1bgo6qw8vjt 
       foreign key (user_id) 
       references users;

    alter table if exists user_role_assignments 
       add constraint FKgn3qd4tmot5ikyaplglaowd9i 
       foreign key (role_id) 
       references user_roles;

    alter table if exists user_role_assignments 
       add constraint FKrb42ra1ptis8nx3g4wotuf003 
       foreign key (user_id) 
       references users;

    create table accounts (
        id bigint not null,
        primary key (id)
    );

    create table role_grantable_roles (
        grantable_role_id bigint not null,
        role_id bigint not null,
        primary key (grantable_role_id, role_id)
    );

    create table sessions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logout_time timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        session_token uuid not null unique,
        ip_address varchar(45),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        user_agent varchar(255),
        primary key (id)
    );

    create table user_role_assignments (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table user_roles (
        id bigint generated by default as identity,
        model_guid uuid not null unique,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        full_name varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKlsevhk46j1mfa8r9bak4tr4x3 
       foreign key (id) 
       references users;

    alter table if exists role_grantable_roles 
       add constraint FKik102cto3k67xqweb7k1vdw7k 
       foreign key (grantable_role_id) 
       references user_roles;

    alter table if exists role_grantable_roles 
       add constraint FKp82b1hlqcctsf88w8fcb31n10 
       foreign key (role_id) 
       references user_roles;

    alter table if exists sessions 
       add constraint FKruie73rneumyyd1bgo6qw8vjt 
       foreign key (user_id) 
       references users;

    alter table if exists user_role_assignments 
       add constraint FKgn3qd4tmot5ikyaplglaowd9i 
       foreign key (role_id) 
       references user_roles;

    alter table if exists user_role_assignments 
       add constraint FKrb42ra1ptis8nx3g4wotuf003 
       foreign key (user_id) 
       references users;

    create table accounts (
        id bigint not null,
        primary key (id)
    );

    create table role_grantable_roles (
        grantable_role_id bigint not null,
        role_id bigint not null,
        primary key (grantable_role_id, role_id)
    );

    create table sessions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        logout_time timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        session_token uuid not null unique,
        ip_address varchar(45),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        user_agent varchar(255),
        primary key (id)
    );

    create table user_role_assignments (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table user_roles (
        id bigint generated by default as identity,
        model_guid uuid not null unique,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        entity_state varchar(255) not null check (entity_state in ('ACTIVE','INACTIVE','TRASHED')),
        full_name varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKlsevhk46j1mfa8r9bak4tr4x3 
       foreign key (id) 
       references users;

    alter table if exists role_grantable_roles 
       add constraint FKik102cto3k67xqweb7k1vdw7k 
       foreign key (grantable_role_id) 
       references user_roles;

    alter table if exists role_grantable_roles 
       add constraint FKp82b1hlqcctsf88w8fcb31n10 
       foreign key (role_id) 
       references user_roles;

    alter table if exists sessions 
       add constraint FKruie73rneumyyd1bgo6qw8vjt 
       foreign key (user_id) 
       references users;

    alter table if exists user_role_assignments 
       add constraint FKgn3qd4tmot5ikyaplglaowd9i 
       foreign key (role_id) 
       references user_roles;

    alter table if exists user_role_assignments 
       add constraint FKrb42ra1ptis8nx3g4wotuf003 
       foreign key (user_id) 
       references users;
